---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Deploy private keys for photofile.ru user
  copy: src={{ item }} dest=/home/photofile.ru/.ssh/ owner=photofile.ru group=w3photofile mode=0400
  with_items:
    - roles/reglament/files/ff_photofile.ru/id_rsa
    - roles/reglament/files/ff_photofile.ru/id_dsa

- name: Create directory for default vhost
  file: path=/www/{{ inventory_hostname }} owner=root group=wheel mode=0775 state=directory
  tags:
    - www
    - nginx

- name: Put index.php in default vhost
  copy: src=files/default_index.php dest=/www/{{ inventory_hostname }}/index.php owner=root group=wheel mode=0664
  tags:
    - www
    - nginx

- name: Copy nginx init.d file
  template: src=templates/init.nginx.j2 dest=/etc/init.d/nginx backup=no owner=root group=wheel mode=755
  when: ansible_system == "Linux"
  tags:
    - nginx
    - www

- name: Run nginx service at boot time
  service: name=nginx enabled=yes
  when: ansible_system == "Linux"
  tags:
    - nginx
    - www

- name: Copy nginx configuration files
  template: src=nginx/{{ item }}.j2 dest={{ NGINX_CONF_DIR }}/{{ item }} backup=no owner=root group=wheel mode=0644
  with_items:
    - nginx.conf
    - nginx.photofile.conf
    - nginx.photofile.face.conf
    - nginx.shot.conf
  notify:
    - reload nginx
  tags:
    - nginx
    - www

#- name: Copy nginx configuration file
#  template: src=nginx.conf.j2 dest=/tmp/ansible-cribs/nginx.conf backup=yes
#  template: src=nginx.conf.j2 dest=/tmp/ansible-cribs/nginx.conf validate='{{ NGINX_SBIN }} -t -c %s' backup=yes
